# Input clock
set_property IOSTANDARD LVCMOS33 [get_ports clk_25mhz]
set_property PACKAGE_PIN E12 [get_ports clk_25mhz]
create_clock -period 40.000 -name clk_25mhz -waveform {0.000 20.000} [get_ports clk_25mhz]

# RGMII bus
set_property PACKAGE_PIN R8 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN R7 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN T7 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN N6 [get_ports {rgmii_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[0]}]
set_property PACKAGE_PIN P9 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN T9 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN T10 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN R10 [get_ports {rgmii_txd[0]}]
set_property PACKAGE_PIN R5 [get_ports eth_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports eth_mdc]
set_property PACKAGE_PIN T5 [get_ports eth_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports eth_mdio]
set_property PULLUP true [get_ports eth_mdio]
set_property PACKAGE_PIN R6 [get_ports eth_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rst_n]
set_property PACKAGE_PIN P6 [get_ports rgmii_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rx_ctl]
set_property PACKAGE_PIN N11 [get_ports rgmii_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxc]
set_property PACKAGE_PIN T8 [get_ports rgmii_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_ctl]
set_property PACKAGE_PIN P8 [get_ports rgmii_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txc]
set_property PULLUP true [get_ports {rgmii_rxd[3]}]
set_property PULLUP true [get_ports {rgmii_rxd[2]}]
set_property PULLUP true [get_ports {rgmii_rxd[1]}]
set_property PULLUP true [get_ports {rgmii_rxd[0]}]
set_property PULLDOWN true [get_ports rgmii_rxc]
create_clock -period 8.000 -name rgmii_rxc -waveform {0.000 4.000} [get_ports rgmii_rxc]

set_property DRIVE 8 [get_ports {rgmii_txd[3]}]
set_property DRIVE 8 [get_ports {rgmii_txd[2]}]
set_property DRIVE 8 [get_ports {rgmii_txd[1]}]
set_property DRIVE 8 [get_ports {rgmii_txd[0]}]
set_property SLEW FAST [get_ports {rgmii_txd[3]}]
set_property SLEW FAST [get_ports {rgmii_txd[2]}]
set_property SLEW FAST [get_ports {rgmii_txd[1]}]
set_property SLEW FAST [get_ports {rgmii_txd[0]}]
set_property DRIVE 12 [get_ports rgmii_txc]
set_property SLEW SLOW [get_ports rgmii_txc]
set_property DRIVE 12 [get_ports rgmii_tx_ctl]
set_property SLEW SLOW [get_ports rgmii_tx_ctl]


# Synchronizer ignores
set_max_delay -from [get_cells -hierarchical *reg_a_ff*] -to [get_cells -hierarchical *reg_b_reg*] 8.000
set_max_delay -from [get_cells -hierarchical *dout0_reg*] -to [get_cells -hierarchical *dout1_reg*] 8.000

# I2C
set_property PACKAGE_PIN H14 [get_ports i2c_sda]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_sda]
set_property PACKAGE_PIN H16 [get_ports i2c_scl]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_scl]
set_property PULLUP true [get_ports i2c_scl]
set_property PULLUP true [get_ports i2c_sda]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_125mhz]

set_clock_groups -asynchronous -group [get_clocks rgmii_rxc] -group [get_clocks clk_100mhz_SystemPLL]
set_clock_groups -asynchronous -group [get_clocks rgmii_rxc] -group [get_clocks clk_125mhz_SystemPLL]
set_clock_groups -asynchronous -group [get_clocks clk_100mhz_SystemPLL] -group [get_clocks rgmii_rxc]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz_SystemPLL] -group [get_clocks rgmii_rxc]
