EESchema Schematic File Version 4
EELAYER 30 0
EELAYER END
$Descr A3 16535 11693
encoding utf-8
Sheet 4 15
Title "MAXWELL Main Board"
Date "2020-06-16"
Rev "0.1"
Comp "Antikernel Labs"
Comment1 "Andrew D. Zonenberg"
Comment2 ""
Comment3 ""
Comment4 ""
$EndDescr
$Comp
L memory-azonenberg:DDR3_SODIMM U3
U 2 1 5EF1FB5C
P 13400 8300
F 0 "U3" H 13900 10975 50  0000 C CNN
F 1 "DDR3_SODIMM" H 13900 10884 50  0000 C CNN
F 2 "" H 13650 8250 50  0001 C CNN
F 3 "" H 13650 8250 50  0001 C CNN
	2    13400 8300
	1    0    0    -1  
$EndComp
$Comp
L memory-azonenberg:DDR3_SODIMM U3
U 3 1 5EF22691
P 13400 5550
F 0 "U3" H 13900 10425 50  0000 C CNN
F 1 "DDR3_SODIMM" H 13900 10334 50  0000 C CNN
F 2 "" H 13650 5500 50  0001 C CNN
F 3 "" H 13650 5500 50  0001 C CNN
	3    13400 5550
	1    0    0    -1  
$EndComp
$Comp
L xilinx-azonenberg:XC7KxT-FFG676 U2
U 11 1 5EF39C8B
P 7900 5850
F 0 "U2" H 7900 5800 50  0000 L CNN
F 1 "XC7K160T-2FFG676C" H 7900 5700 50  0000 L CNN
F 2 "" H 7900 5850 50  0001 C CNN
F 3 "" H 7900 5850 50  0001 C CNN
	11   7900 5850
	1    0    0    -1  
$EndComp
$Comp
L xilinx-azonenberg:XC7KxT-FFG676 U2
U 10 1 5EF876C9
P 5350 5850
F 0 "U2" H 5350 5800 50  0000 L CNN
F 1 "XC7K160T-2FFG676C" H 5350 5700 50  0000 L CNN
F 2 "" H 5350 5850 50  0001 C CNN
F 3 "" H 5350 5850 50  0001 C CNN
	10   5350 5850
	1    0    0    -1  
$EndComp
$Comp
L xilinx-azonenberg:XC7KxT-FFG676 U2
U 9 1 5EF93AD3
P 2350 5850
F 0 "U2" H 2350 5800 50  0000 L CNN
F 1 "XC7K160T-2FFG676C" H 2350 5700 50  0000 L CNN
F 2 "" H 2350 5850 50  0001 C CNN
F 3 "" H 2350 5850 50  0001 C CNN
	9    2350 5850
	1    0    0    -1  
$EndComp
Text HLabel 10100 1700 0    50   Input ~ 0
1V5
Text HLabel 10100 3600 0    50   Input ~ 0
GND
Text HLabel 1600 2100 0    50   Input ~ 0
RAM_VREF
Text HLabel 10100 1400 0    50   Input ~ 0
RAM_VTT
Text Notes 2650 8050 0    50   ~ 0
Rzq = 240 ohms\n40 ohm line impedance\nMIG wants 800 MHz input clock
Text Notes 5350 6150 0    50   ~ 0
Bank 33 = addr/control
Text Notes 7900 6150 0    50   ~ 0
Bank 34 = DQ[31:0]
Text Notes 2350 6150 0    50   ~ 0
Bank 32 = DQ[63:32]
Text Label 7700 1100 2    50   ~ 0
DDR_DQ0
Text Label 7700 1200 2    50   ~ 0
DDR_DQ1
Text Label 7700 1300 2    50   ~ 0
DDR_DQ2
Text Label 7700 1600 2    50   ~ 0
DDR_DQ3
Text Label 7700 1700 2    50   ~ 0
DDR_DQ4
Text Label 7700 1800 2    50   ~ 0
DDR_DQ5
Text Label 7700 1900 2    50   ~ 0
DDR_DQ6
Text Label 7700 2000 2    50   ~ 0
DDR_DQ7
Text Label 7700 2300 2    50   ~ 0
DDR_DQ8
Text Label 7700 2400 2    50   ~ 0
DDR_DQ9
Text Label 7700 2500 2    50   ~ 0
DDR_DQ10
Text Notes 7900 800  0    50   ~ 0
Pinout generated by MIG\nCan swap entire byte groups for routability,\nor DQ lines within a byte group
Text Label 7700 2800 2    50   ~ 0
DDR_DQ11
Text Label 7700 2900 2    50   ~ 0
DDR_DQ12
Text Label 7700 3000 2    50   ~ 0
DDR_DQ13
Text Label 7700 3100 2    50   ~ 0
DDR_DQ14
Text Label 7700 3200 2    50   ~ 0
DDR_DQ15
Text Label 7700 3400 2    50   ~ 0
DDR_DQ16
Text Label 7700 3500 2    50   ~ 0
DDR_DQ17
Text Label 7700 3600 2    50   ~ 0
DDR_DQ18
Text Label 7700 3700 2    50   ~ 0
DDR_DQ19
Text Label 7700 4100 2    50   ~ 0
DDR_DQ20
Text Label 7700 4200 2    50   ~ 0
DDR_DQ21
Text Label 7700 4300 2    50   ~ 0
DDR_DQ22
Text Label 7700 4400 2    50   ~ 0
DDR_DQ23
Text Label 7700 4800 2    50   ~ 0
DDR_DQ24
Text Label 7700 4900 2    50   ~ 0
DDR_DQ25
Text Label 7700 5200 2    50   ~ 0
DDR_DQ26
Text Label 7700 5300 2    50   ~ 0
DDR_DQ27
Text Label 7700 5400 2    50   ~ 0
DDR_DQ28
Text Label 7700 5500 2    50   ~ 0
DDR_DQ29
Text Label 7700 5600 2    50   ~ 0
DDR_DQ30
Text Label 7700 5700 2    50   ~ 0
DDR_DQ31
Text Label 2150 1100 2    50   ~ 0
DDR_DQ32
Text Label 2150 1200 2    50   ~ 0
DDR_DQ33
Text Label 2150 1300 2    50   ~ 0
DDR_DQ34
Text Label 2150 1600 2    50   ~ 0
DDR_DQ35
Text Label 2150 1700 2    50   ~ 0
DDR_DQ36
Text Label 2150 1800 2    50   ~ 0
DDR_DQ37
Text Label 2150 1900 2    50   ~ 0
DDR_DQ38
Text Label 2150 2000 2    50   ~ 0
DDR_DQ39
Text Label 2150 2300 2    50   ~ 0
DDR_DQ40
Text Label 2150 2400 2    50   ~ 0
DDR_DQ41
Text Label 2150 2500 2    50   ~ 0
DDR_DQ42
Text Label 2150 2800 2    50   ~ 0
DDR_DQ43
Text Label 2150 2900 2    50   ~ 0
DDR_DQ44
Text Label 2150 3000 2    50   ~ 0
DDR_DQ45
Text Label 2150 3100 2    50   ~ 0
DDR_DQ46
Text Label 2150 3200 2    50   ~ 0
DDR_DQ47
Text Label 2150 3400 2    50   ~ 0
DDR_DQ48
Text Label 2150 3500 2    50   ~ 0
DDR_DQ49
Text Label 2150 3600 2    50   ~ 0
DDR_DQ50
Text Label 2150 3700 2    50   ~ 0
DDR_DQ51
Text Label 2150 4100 2    50   ~ 0
DDR_DQ52
Text Label 2150 4200 2    50   ~ 0
DDR_DQ53
Text Label 2150 4300 2    50   ~ 0
DDR_DQ54
Text Label 2150 4400 2    50   ~ 0
DDR_DQ55
Text Label 2150 4800 2    50   ~ 0
DDR_DQ56
Text Label 2150 4900 2    50   ~ 0
DDR_DQ57
Text Label 2150 5200 2    50   ~ 0
DDR_DQ58
Text Label 2150 5300 2    50   ~ 0
DDR_DQ59
Text Label 2150 5400 2    50   ~ 0
DDR_DQ60
Text Label 2150 5500 2    50   ~ 0
DDR_DQ61
Text Label 2150 5600 2    50   ~ 0
DDR_DQ62
Text Label 2150 5700 2    50   ~ 0
DDR_DQ63
Text Label 5150 1000 2    50   ~ 0
DDR_A15
Text Label 5150 1100 2    50   ~ 0
DDR_A14
Text Label 5150 1200 2    50   ~ 0
DDR_A13
Text Label 5150 1300 2    50   ~ 0
DDR_A12
Text Label 5150 1600 2    50   ~ 0
DDR_A11
Text Label 5150 1700 2    50   ~ 0
DDR_A10
Text Label 5150 1800 2    50   ~ 0
DDR_A9
Text Label 5150 1900 2    50   ~ 0
DDR_A8
Text Label 5150 2000 2    50   ~ 0
DDR_A7
Text Label 5150 2100 2    50   ~ 0
DDR_A6
Text Label 5150 2200 2    50   ~ 0
DDR_A5
Text Label 5150 2300 2    50   ~ 0
DDR_A4
Text Label 5150 2400 2    50   ~ 0
DDR_A3
Text Label 5150 2500 2    50   ~ 0
DDR_A2
Text Label 5150 2600 2    50   ~ 0
DDR_A1
Text Label 5150 2700 2    50   ~ 0
DDR_A0
Text Label 5150 2800 2    50   ~ 0
DDR_BA2
Text Label 5150 2900 2    50   ~ 0
DDR_BA1
Text Label 5150 3000 2    50   ~ 0
DDR_BA0
Text Label 5150 3100 2    50   ~ 0
DDR_RAS_N
Text Label 5150 3200 2    50   ~ 0
DDR_CAS_N
Text Label 5150 3300 2    50   ~ 0
DDR_WE_N
Text Label 7700 3300 2    50   ~ 0
DDR_RST_N
Text Label 5150 3900 2    50   ~ 0
DDR_CKE_0
Text Label 5150 4000 2    50   ~ 0
DDR_ODT_0
Text Label 5150 3800 2    50   ~ 0
DDR_CS_N_0
Text Label 7700 1000 2    50   ~ 0
DDR_DM0
Text Label 7700 2200 2    50   ~ 0
DDR_DM1
Text Label 7700 4000 2    50   ~ 0
DDR_DM2
Text Label 7700 4600 2    50   ~ 0
DDR_DM3
Text Label 2150 1000 2    50   ~ 0
DDR_DM4
Text Label 2150 2200 2    50   ~ 0
DDR_DM5
Text Label 2150 4000 2    50   ~ 0
DDR_DM6
Text Label 2150 4600 2    50   ~ 0
DDR_DM7
Text Label 7700 1400 2    50   ~ 0
DDR_DQS0_P
Text Label 7700 1500 2    50   ~ 0
DDR_DQS0_N
Text Label 7700 2600 2    50   ~ 0
DDR_DQS1_P
Text Label 7700 2700 2    50   ~ 0
DDR_DQS1_N
Text Label 7700 3800 2    50   ~ 0
DDR_DQS2_P
Text Label 7700 3900 2    50   ~ 0
DDR_DQS2_N
Text Label 7700 5000 2    50   ~ 0
DDR_DQS3_P
Text Label 7700 5100 2    50   ~ 0
DDR_DQS3_N
Text Label 2150 1400 2    50   ~ 0
DDR_DQS4_P
Text Label 2150 1500 2    50   ~ 0
DDR_DQS4_N
Text Label 2150 2600 2    50   ~ 0
DDR_DQS5_P
Text Label 2150 2700 2    50   ~ 0
DDR_DQS5_N
Text Label 2150 3800 2    50   ~ 0
DDR_DQS6_P
Text Label 2150 3900 2    50   ~ 0
DDR_DQS6_N
Text Label 2150 5000 2    50   ~ 0
DDR_DQS7_P
Text Label 2150 5100 2    50   ~ 0
DDR_DQS7_N
Text Label 5150 1400 2    50   ~ 0
DDR_CLK0_P
Text Label 5150 1500 2    50   ~ 0
DDR_CLK0_N
Text Label 14600 1200 0    50   ~ 0
DDR_DQ32
Text Label 14600 1300 0    50   ~ 0
DDR_DQ33
Text Label 14600 1400 0    50   ~ 0
DDR_DQ34
Text Label 14600 1500 0    50   ~ 0
DDR_DQ35
Text Label 14600 1600 0    50   ~ 0
DDR_DQ36
Text Label 14600 1700 0    50   ~ 0
DDR_DQ37
Text Label 14600 1800 0    50   ~ 0
DDR_DQ38
Text Label 14600 1900 0    50   ~ 0
DDR_DQ39
Text Label 14600 2400 0    50   ~ 0
DDR_DQ40
Text Label 14600 2500 0    50   ~ 0
DDR_DQ41
Text Label 14600 2600 0    50   ~ 0
DDR_DQ42
Text Label 14600 2700 0    50   ~ 0
DDR_DQ43
Text Label 14600 2800 0    50   ~ 0
DDR_DQ44
Text Label 14600 2900 0    50   ~ 0
DDR_DQ45
Text Label 14600 3000 0    50   ~ 0
DDR_DQ46
Text Label 14600 3100 0    50   ~ 0
DDR_DQ47
Text Label 14600 3600 0    50   ~ 0
DDR_DQ48
Text Label 14600 3700 0    50   ~ 0
DDR_DQ49
Text Label 14600 3800 0    50   ~ 0
DDR_DQ50
Text Label 14600 3900 0    50   ~ 0
DDR_DQ51
Text Label 14600 4000 0    50   ~ 0
DDR_DQ52
Text Label 14600 4100 0    50   ~ 0
DDR_DQ53
Text Label 14600 4200 0    50   ~ 0
DDR_DQ54
Text Label 14600 4300 0    50   ~ 0
DDR_DQ55
Text Label 14600 4800 0    50   ~ 0
DDR_DQ56
Text Label 14600 4900 0    50   ~ 0
DDR_DQ57
Text Label 14600 5000 0    50   ~ 0
DDR_DQ58
Text Label 14600 5100 0    50   ~ 0
DDR_DQ59
Text Label 14600 5200 0    50   ~ 0
DDR_DQ60
Text Label 14600 5300 0    50   ~ 0
DDR_DQ61
Text Label 14600 5400 0    50   ~ 0
DDR_DQ62
Text Label 14600 5500 0    50   ~ 0
DDR_DQ63
Text Label 14600 1100 0    50   ~ 0
DDR_DM4
Text Label 14600 2300 0    50   ~ 0
DDR_DM5
Text Label 14600 3500 0    50   ~ 0
DDR_DM6
Text Label 14600 4700 0    50   ~ 0
DDR_DM7
Text Label 14600 900  0    50   ~ 0
DDR_DQS4_P
Text Label 14600 1000 0    50   ~ 0
DDR_DQS4_N
Text Label 14600 2100 0    50   ~ 0
DDR_DQS5_P
Text Label 14600 2200 0    50   ~ 0
DDR_DQS5_N
Text Label 14600 3300 0    50   ~ 0
DDR_DQS6_P
Text Label 14600 3400 0    50   ~ 0
DDR_DQS6_N
Text Label 14600 4500 0    50   ~ 0
DDR_DQS7_P
Text Label 14600 4600 0    50   ~ 0
DDR_DQS7_N
Text Label 14600 8250 0    50   ~ 0
DDR_A15
Text Label 14600 8150 0    50   ~ 0
DDR_A14
Text Label 14600 8050 0    50   ~ 0
DDR_A13
Text Label 14600 7950 0    50   ~ 0
DDR_A12
Text Label 14600 7850 0    50   ~ 0
DDR_A11
Text Label 14600 7750 0    50   ~ 0
DDR_A10
Text Label 14600 7650 0    50   ~ 0
DDR_A9
Text Label 14600 7550 0    50   ~ 0
DDR_A8
Text Label 14600 7450 0    50   ~ 0
DDR_A7
Text Label 14600 7350 0    50   ~ 0
DDR_A6
Text Label 14600 7250 0    50   ~ 0
DDR_A5
Text Label 14600 7150 0    50   ~ 0
DDR_A4
Text Label 14600 7050 0    50   ~ 0
DDR_A3
Text Label 14600 6950 0    50   ~ 0
DDR_A2
Text Label 14600 6850 0    50   ~ 0
DDR_A1
Text Label 14600 6750 0    50   ~ 0
DDR_A0
Text Label 14600 6550 0    50   ~ 0
DDR_BA2
Text Label 14600 6450 0    50   ~ 0
DDR_BA1
Text Label 14600 6350 0    50   ~ 0
DDR_BA0
Text Label 13200 8250 2    50   ~ 0
DDR_RAS_N
Text Label 13200 8150 2    50   ~ 0
DDR_CAS_N
Text Label 13200 8050 2    50   ~ 0
DDR_WE_N
Text Label 13200 6650 2    50   ~ 0
DDR_CKE_0
Text Label 13200 7750 2    50   ~ 0
DDR_ODT_0
Text Label 13200 7450 2    50   ~ 0
DDR_CS_N_0
Text Label 13200 6750 2    50   ~ 0
DDR_CLK0_P
Text Label 13200 6850 2    50   ~ 0
DDR_CLK0_N
Text Label 13200 1200 2    50   ~ 0
DDR_DQ0
Text Label 13200 1300 2    50   ~ 0
DDR_DQ1
Text Label 13200 1400 2    50   ~ 0
DDR_DQ2
Text Label 13200 1500 2    50   ~ 0
DDR_DQ3
Text Label 13200 1600 2    50   ~ 0
DDR_DQ4
Text Label 13200 1700 2    50   ~ 0
DDR_DQ5
Text Label 13200 1800 2    50   ~ 0
DDR_DQ6
Text Label 13200 1900 2    50   ~ 0
DDR_DQ7
Text Label 13200 2400 2    50   ~ 0
DDR_DQ8
Text Label 13200 2500 2    50   ~ 0
DDR_DQ9
Text Label 13200 2600 2    50   ~ 0
DDR_DQ10
Text Label 13200 2700 2    50   ~ 0
DDR_DQ11
Text Label 13200 2800 2    50   ~ 0
DDR_DQ12
Text Label 13200 2900 2    50   ~ 0
DDR_DQ13
Text Label 13200 3000 2    50   ~ 0
DDR_DQ14
Text Label 13200 3100 2    50   ~ 0
DDR_DQ15
Text Label 13200 3600 2    50   ~ 0
DDR_DQ16
Text Label 13200 3700 2    50   ~ 0
DDR_DQ17
Text Label 13200 3800 2    50   ~ 0
DDR_DQ18
Text Label 13200 3900 2    50   ~ 0
DDR_DQ19
Text Label 13200 4000 2    50   ~ 0
DDR_DQ20
Text Label 13200 4100 2    50   ~ 0
DDR_DQ21
Text Label 13200 4200 2    50   ~ 0
DDR_DQ22
Text Label 13200 4300 2    50   ~ 0
DDR_DQ23
Text Label 13200 4800 2    50   ~ 0
DDR_DQ24
Text Label 13200 4900 2    50   ~ 0
DDR_DQ25
Text Label 13200 5000 2    50   ~ 0
DDR_DQ26
Text Label 13200 5100 2    50   ~ 0
DDR_DQ27
Text Label 13200 5200 2    50   ~ 0
DDR_DQ28
Text Label 13200 5300 2    50   ~ 0
DDR_DQ29
Text Label 13200 5400 2    50   ~ 0
DDR_DQ30
Text Label 13200 5500 2    50   ~ 0
DDR_DQ31
Text Label 13200 6450 2    50   ~ 0
DDR_RST_N
Text Label 13200 1100 2    50   ~ 0
DDR_DM0
Text Label 13200 2300 2    50   ~ 0
DDR_DM1
Text Label 13200 3500 2    50   ~ 0
DDR_DM2
Text Label 13200 4700 2    50   ~ 0
DDR_DM3
Text Label 13200 900  2    50   ~ 0
DDR_DQS0_P
Text Label 13200 1000 2    50   ~ 0
DDR_DQS0_N
Text Label 13200 2100 2    50   ~ 0
DDR_DQS1_P
Text Label 13200 2200 2    50   ~ 0
DDR_DQS1_N
Text Label 13200 3300 2    50   ~ 0
DDR_DQS2_P
Text Label 13200 3400 2    50   ~ 0
DDR_DQS2_N
Text Label 13200 4500 2    50   ~ 0
DDR_DQS3_P
Text Label 13200 4600 2    50   ~ 0
DDR_DQS3_N
NoConn ~ 2150 900 
NoConn ~ 2150 3300
NoConn ~ 2150 4500
NoConn ~ 2150 5800
Wire Wire Line
	1600 2100 2150 2100
Text Label 2150 4700 2    50   ~ 0
RAM_VREF
Text Label 7700 4700 2    50   ~ 0
RAM_VREF
Text Label 7700 2100 2    50   ~ 0
RAM_VREF
NoConn ~ 7700 900 
NoConn ~ 7700 4500
NoConn ~ 7700 5800
NoConn ~ 5150 900 
NoConn ~ 5150 3400
NoConn ~ 5150 3500
NoConn ~ 5150 3600
NoConn ~ 5150 3700
NoConn ~ 5150 4100
NoConn ~ 5150 4200
NoConn ~ 5150 4300
NoConn ~ 5150 4400
NoConn ~ 5150 4500
NoConn ~ 5150 4600
NoConn ~ 5150 4700
NoConn ~ 5150 4800
NoConn ~ 5150 4900
NoConn ~ 5150 5000
NoConn ~ 5150 5100
NoConn ~ 5150 5200
NoConn ~ 5150 5300
NoConn ~ 5150 5400
NoConn ~ 5150 5500
NoConn ~ 5150 5600
NoConn ~ 5150 5700
NoConn ~ 5150 5800
$Comp
L memory-azonenberg:DDR3_SODIMM U3
U 1 1 600B7F75
P 10300 4850
F 0 "U3" H 10800 9025 50  0000 C CNN
F 1 "DDR3_SODIMM" H 10800 8934 50  0000 C CNN
F 2 "" H 10550 4800 50  0001 C CNN
F 3 "" H 10550 4800 50  0001 C CNN
	1    10300 4850
	1    0    0    -1  
$EndComp
Text HLabel 10100 900  0    50   Output ~ 0
3V3
Text Label 10100 1100 2    50   ~ 0
RAM_VREF
Wire Wire Line
	10100 1100 10100 1200
Wire Wire Line
	10100 1400 10100 1500
Wire Wire Line
	10100 1700 10100 1800
Connection ~ 10100 1800
Wire Wire Line
	10100 1800 10100 1900
Connection ~ 10100 1900
Wire Wire Line
	10100 1900 10100 2000
Connection ~ 10100 2000
Wire Wire Line
	10100 2000 10100 2100
Connection ~ 10100 2100
Wire Wire Line
	10100 2100 10100 2200
Connection ~ 10100 2200
Wire Wire Line
	10100 2200 10100 2300
Connection ~ 10100 2300
Wire Wire Line
	10100 2300 10100 2400
Connection ~ 10100 2400
Wire Wire Line
	10100 2400 10100 2500
Connection ~ 10100 2500
Wire Wire Line
	10100 2500 10100 2600
Connection ~ 10100 2600
Wire Wire Line
	10100 2600 10100 2700
Connection ~ 10100 2700
Wire Wire Line
	10100 2700 10100 2800
Connection ~ 10100 2800
Wire Wire Line
	10100 2800 10100 2900
Connection ~ 10100 2900
Wire Wire Line
	10100 2900 10100 3000
Connection ~ 10100 3000
Wire Wire Line
	10100 3000 10100 3100
Connection ~ 10100 3100
Wire Wire Line
	10100 3100 10100 3200
Connection ~ 10100 3200
Wire Wire Line
	10100 3200 10100 3300
Connection ~ 10100 3300
Wire Wire Line
	10100 3300 10100 3400
Wire Wire Line
	10100 3600 10100 3700
Connection ~ 10100 3700
Wire Wire Line
	10100 3700 10100 3800
Connection ~ 10100 3800
Wire Wire Line
	10100 3800 10100 3900
Connection ~ 10100 3900
Wire Wire Line
	10100 3900 10100 4000
Connection ~ 10100 4000
Wire Wire Line
	10100 4000 10100 4100
Connection ~ 10100 4100
Wire Wire Line
	10100 4100 10100 4200
Connection ~ 10100 4200
Wire Wire Line
	10100 4200 10100 4300
Connection ~ 10100 4300
Wire Wire Line
	10100 4300 10100 4400
Connection ~ 10100 4400
Wire Wire Line
	10100 4400 10100 4500
Connection ~ 10100 4500
Wire Wire Line
	10100 4500 10100 4600
Connection ~ 10100 4600
Wire Wire Line
	10100 4600 10100 4700
Connection ~ 10100 4700
Wire Wire Line
	10100 4700 10100 4800
Text Label 11500 900  0    50   ~ 0
GND
Wire Wire Line
	11500 900  11500 1000
Connection ~ 11500 1000
Wire Wire Line
	11500 1000 11500 1100
Connection ~ 11500 1100
Wire Wire Line
	11500 1100 11500 1200
Connection ~ 11500 1200
Wire Wire Line
	11500 1200 11500 1300
Connection ~ 11500 1300
Wire Wire Line
	11500 1300 11500 1400
Connection ~ 11500 1400
Wire Wire Line
	11500 1400 11500 1500
Connection ~ 11500 1500
Wire Wire Line
	11500 1500 11500 1600
Connection ~ 11500 1600
Wire Wire Line
	11500 1600 11500 1700
Connection ~ 11500 1700
Wire Wire Line
	11500 1700 11500 1800
Connection ~ 11500 1800
Wire Wire Line
	11500 1800 11500 1900
Connection ~ 11500 1900
Wire Wire Line
	11500 1900 11500 2000
Connection ~ 11500 2000
Wire Wire Line
	11500 2000 11500 2100
Connection ~ 11500 2100
Wire Wire Line
	11500 2100 11500 2200
Connection ~ 11500 2200
Wire Wire Line
	11500 2200 11500 2300
Connection ~ 11500 2300
Wire Wire Line
	11500 2300 11500 2400
Connection ~ 11500 2400
Wire Wire Line
	11500 2400 11500 2500
Connection ~ 11500 2500
Wire Wire Line
	11500 2500 11500 2600
Connection ~ 11500 2600
Wire Wire Line
	11500 2600 11500 2700
Connection ~ 11500 2700
Wire Wire Line
	11500 2700 11500 2800
Connection ~ 11500 2800
Wire Wire Line
	11500 2800 11500 2900
Connection ~ 11500 2900
Wire Wire Line
	11500 2900 11500 3000
Connection ~ 11500 3000
Wire Wire Line
	11500 3000 11500 3100
Connection ~ 11500 3100
Wire Wire Line
	11500 3100 11500 3200
Connection ~ 11500 3200
Wire Wire Line
	11500 3200 11500 3300
Connection ~ 11500 3300
Wire Wire Line
	11500 3300 11500 3400
Connection ~ 11500 3400
Wire Wire Line
	11500 3400 11500 3500
Connection ~ 11500 3500
Wire Wire Line
	11500 3500 11500 3600
Connection ~ 11500 3600
Wire Wire Line
	11500 3600 11500 3700
Connection ~ 11500 3700
Wire Wire Line
	11500 3700 11500 3800
Connection ~ 11500 3800
Wire Wire Line
	11500 3800 11500 3900
Connection ~ 11500 3900
Wire Wire Line
	11500 3900 11500 4000
Connection ~ 11500 4000
Wire Wire Line
	11500 4000 11500 4100
Connection ~ 11500 4100
Wire Wire Line
	11500 4100 11500 4200
Connection ~ 11500 4200
Wire Wire Line
	11500 4200 11500 4300
Connection ~ 11500 4300
Wire Wire Line
	11500 4300 11500 4400
Connection ~ 11500 4400
Wire Wire Line
	11500 4400 11500 4500
Connection ~ 11500 4500
Wire Wire Line
	11500 4500 11500 4600
Connection ~ 11500 4600
Wire Wire Line
	11500 4600 11500 4700
Text Notes 6200 7850 0    50   ~ 0
TODO: decoupling for SODIMM power, Vref, Vtt
$EndSCHEMATC
