set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN H12 [get_ports {led[3]}]
set_property PACKAGE_PIN H13 [get_ports {led[2]}]
set_property PACKAGE_PIN J16 [get_ports {led[1]}]
set_property PACKAGE_PIN J15 [get_ports {led[0]}]
set_property PACKAGE_PIN T4 [get_ports {probe_p[7]}]
set_property PACKAGE_PIN R2 [get_ports {probe_p[6]}]
set_property PACKAGE_PIN P4 [get_ports {probe_p[5]}]
set_property PACKAGE_PIN N1 [get_ports {probe_p[4]}]
set_property PACKAGE_PIN M5 [get_ports {probe_p[3]}]
set_property PACKAGE_PIN N3 [get_ports {probe_p[2]}]
set_property PACKAGE_PIN L4 [get_ports {probe_p[1]}]
set_property PACKAGE_PIN M2 [get_ports {probe_p[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25mhz]
set_property PACKAGE_PIN E12 [get_ports clk_25mhz]
set_property PACKAGE_PIN E16 [get_ports presence_detect]
set_property PACKAGE_PIN F14 [get_ports power_en]
set_property PACKAGE_PIN F13 [get_ports uart_rx]
set_property PACKAGE_PIN G16 [get_ports uart_tx]

create_clock -period 40.000 -name clk_25mhz -waveform {0.000 20.000} [get_ports clk_25mhz]

set_property IOSTANDARD LVCMOS33 [get_ports power_en]
set_property IOSTANDARD LVCMOS33 [get_ports presence_detect]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]

set_property PULLUP true [get_ports presence_detect]
